---
name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Run PHPStan
        run: php ./vendor/bin/phpstan analyse -c phpstan.dist.neon


  phpcsfixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Run PHP-CS-Fixer
        run: php ./vendor/bin/php-cs-fixer check
